Debug image andriy
Vskesha/ImageIQ pull request #6
Opened 2024-01-13 16:26 UTC by AndriyBatig1992

Fixed images

2024-01-13 19:55 UTC, Vskesha requested changes

2024-01-13 19:55 UTC, Vskesha commented on src/database/models.py
Як зможеш, то додай тут порожній рядок

2024-01-13 19:55 UTC, Vskesha commented on src/repository/images.py
> +
+++

2024-01-13 19:55 UTC, Vskesha commented on src/routes/images.py
>          'tags': image.tags,
+++

2024-01-13 19:55 UTC, Vskesha commented on src/services/cloud_image.py
> +
+++

2024-01-13 19:55 UTC, Vskesha commented on src/services/cloud_image.py
> +        break_point = old_link.find('/upload/') + 8
+++

2024-01-13 19:55 UTC, Vskesha commented on src/routes/images.py
>      transform_image_link = CloudImage.transformation(image, type)
Андрій глянь на 124 рядок (type: TransformationsType). Звідки type буде братись в функції обробнику. Може  передавати його через роут типу 115 рядок замінити з 
@router.post('/transaction/{image_id}', на 
@router.post('/transaction/{image_id}/{type}',
і перевіряти чи він є у списку доступних значень

2024-01-14 12:16 UTC, AndriyBatig1992 commented on src/routes/images.py
>      transform_image_link = CloudImage.transformation(image, type)
так ти правий..поправ на @router.post('/transaction/{image_id}/{type}

2024-01-15 08:25 UTC, Vskesha approved these changes

2024-01-15 08:25 UTC, Vskesha commented on src/routes/auth.py
> +    except HTTPException as e:
Потім попрацюємо над відповідями. Але думаю краще повертати як типу {''message": "You have logged out!!!"}

2024-01-15 08:25 UTC, Vskesha commented on main.py
>  from src.conf.config import settings
Поправив імпорти

2024-01-15 08:25 UTC, Vskesha commented on main.py
підключив роути коментів

2024-01-15 08:25 UTC, Vskesha commented on src/conf/messages.py
> +MSC404_COMMENT_NOT_FOUND = "Comment Not Found"
added absent fields

2024-01-15 08:25 UTC, Vskesha commented on src/database/models.py
fixed imports

2024-01-15 08:25 UTC, Vskesha commented on src/repository/comments.py
> +from src.schemas.images import CommentModel
fixed imports

2024-01-15 08:25 UTC, Vskesha commented on src/routes/auth.py
>  from src.services.auth import auth_service
fixed imports

2024-01-15 08:25 UTC, Vskesha commented on src/routes/comments.py
> +from src.services.role import allowed_all_roles_access, allowed_admin_moderator
fixed imports

2024-01-15 08:26 UTC, merged